### ISSUE TITLE
Source connector worker task is getting stuck and not publishing any records

### ISSUE THREAD

**Issue by SiddarthSingh** [camunda-community-hub/kafka-connect-zeebe#61]
worker task is getting stuck and not producing any records to kafka topic in case if there is a bad/malformed record present in the pipeline.

Step to reproduce:

1. Try creating a process instance of a bpmn process without providing kafka topic header (or provide any topic which doesn't exist in kafka).
2.  Create instances of other bpmn process where topics are provided and exist in kafka.
3. Following error is reported in kafka connect log and its not processing any record from zeebe.

06:34:01.044 [task-thread-go-source-0] o.a.k.c.r.WorkerTask ERROR - WorkerSourceTask{id=go-source-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted org.apache.kafka.connect.errors.ConnectException: Unrecoverable exception from producer send callback
        at org.apache.kafka.connect.runtime.WorkerSourceTask.maybeThrowProducerSendException(WorkerSourceTask.java:266)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:320)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:248)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:182)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:231)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.common.errors.TimeoutException: Topic ota-topics not present in metadata after 30000 ms.

06:34:30.085 [SourceTaskOffsetCommitter-1] o.a.k.c.r.WorkerSourceTask ERROR - WorkerSourceTask{id=go-source-0} Failed to flush, timed out while waiting for producer to flush outstanding 1 messages
06:34:30.085 [SourceTaskOffsetCommitter-1] o.a.k.c.r.SourceTaskOffsetCommitter ERROR - WorkerSourceTask{id=go-source-0} Failed to commit offsets
06:35:35.086 [SourceTaskOffsetCommitter-1] o.a.k.c.r.WorkerSourceTask ERROR - WorkerSourceTask{id=go-source-0} Failed to flush, timed out while waiting for producer to flush outstanding 1 messages
06:35:35.086 [SourceTaskOffsetCommitter-1] o.a.k.c.r.SourceTaskOffsetCommitter ERROR - WorkerSourceTask{id=go-source-0} Failed to commit offsets
06:36:40.086 [SourceTaskOffsetCommitter-1] o.a.k.c.r.WorkerSourceTask ERROR - WorkerSourceTask{id=go-source-0} Failed to flush, timed out while waiting for producer to flush outstanding 1 messages

Expectation:
zeebe-kafka-connect should throw the error for any bad/malformed records but should continue with the processing of other records which are valid by skipping all bad records from the pipeline/buffer.

**Comment by SiddarthSingh** [comment]
update : Tried setting "errors.tolerance" : "all" for connector config but still same issue.

**Comment by SiddarthSingh** [comment]
update : was able to resolve this finally by adding below properties in connector config:

  "producer.delivery.timeout.ms": "20000"
  "producer.max.block.ms": "60000"
  "producer.request.timeout.ms": "15000"
  "errors.tolerance": "all"

**Comment by SiddarthSingh** [comment]
update : was able to resolve this finally by adding below properties in connector config:

  "producer.delivery.timeout.ms": "20000"
  "producer.max.block.ms": "60000"
  "producer.request.timeout.ms": "15000"
  "errors.tolerance": "all"

**Comment by SiddarthSingh** [comment]
issue is re-occuring intermittently
